export const ClassesDummyData = [
  {
    name: 'Yoga Foundation',
    instructor: 'Bob Dylan',
    type: 'Yoga',
    date: 'October 19, 2021',
    time: '8:00 AM',
    duration: '1:00',
    intensity: 'Beginner',
    location: 'Antarctica',
    attendees: '30',
    max: '50',
  },
  {
    name: 'Cardio Challenge',
    instructor: 'Jon Snow',
    type: 'Cycling',
    date: 'October 22, 2021',
    time: '9:30 AM',
    duration: '1:00',
    intensity: 'Moderate',
    location: 'Mars',
    attendees: '15',
    max: '50',
  },
];
